// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecynsgnuxluznktajahl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjeW5zZ251eGx1em5rdGFqYWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MDMzNzUsImV4cCI6MjA1MDI3OTM3NX0.XtGIux3qTOfO2H2P9gU5zH3gDGDlg1TFPiVLuyZuvE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);